name: Build ALboot

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, i686, aarch64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version
        id: version
        run: echo "VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Install qemu-user-static
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          sudo -E ./build.sh

      - name: Prepare artifact
        run: |
          mkdir palen1x
          cp work/*-${{ matrix.arch }}.iso ALboot
          cp work/iso/boot/initramfs.xz ALboot

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}
          path: ALboot
          
      - name: Generate release tag
        id: tag
        run: |
         echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
          
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          draft: false
          files: work/*.iso
         
    permissions:
      contents: write
          
            


